setxkbmap -model "pc105" -layout us
xmodmap -e "remove mod1 = Alt_L Meta_L"
xmodmap -e "remove mod4 = Super_L"
xmodmap -e "add mod1 = Super_L"
xmodmap -e "add mod4 = Alt_L Meta_L"
xmodmap -e "remove mod1 = Alt_R Meta_R"
xmodmap -e "remove mod4 = Super_R"
xmodmap -e "add mod1 = Super_R"
xmodmap -e "add mod4 = Alt_R Meta_R"
xmodmap -e "keycode 133 = Alt_L Meta_L" 
xmodmap -e "keycode 134 = Alt_R Meta_R" 
xmodmap -e "keycode 108 = Super_R" 
xmodmap -e "keycode 146 = Help"
